Check links better

diff --git a/.github/workflows/check_links.yaml b/.github/workflows/check_links.yaml
--- a/.github/workflows/check_links.yaml
+++ b/.github/workflows/check_links.yaml
@@ -1,3 +1,5 @@
+# Check links on the 20st day of the month.
+# 20st as the first letter of this repo is the 20st letter in the alphabet.
 on:
   push:
   pull_request:
@@ -14,6 +16,26 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
+      # The link checker will only work if mlc_config.json is a valid JSON
+      - name: Validate JSON
+        uses: docker://orrosenblatt/validate-json-action:latest
+        env:
+          INPUT_SCHEMA: .github/workflows/valid_json_schema.json
+          INPUT_JSONS: mlc_config.json
+
+      # These are status code that cannot be ignored.
+      #
+      # If there is a valid external link that fails,
+      # add it to mlc_config.json
+      - name: External links must be checked, do not allow '0' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]0[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
+
+      - name: Internal links must checked, do not allow '400' in the 'aliveStatusCodes' of mlc_config.json
+        run: if [[ $(grep --regexp "[^0-9]400[^0-9]" mlc_config.json | wc --lines) == "1" ]]; then echo "FOUND"; exit 42; fi
+
       - uses: gaurav-nelson/github-action-markdown-link-check@v1
         with:
           config-file: 'mlc_config.json'
+          use-quiet-mode: 'yes'
+          use-verbose-mode: 'no'
+
